name: GoTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2 
        with:
          go-version: 1.17

      - name: linter
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.2

      - name: Build
        run: |
          export GO111MODULE=on
          go mod tidy -compat=1.17
          make qng

      - name: Test
        run: |
          PATH=$PATH:$(pwd)/build/bin
          go test -v ./...
      
      - name: Run ci.sh
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: ./ci.sh
